In [8]:
import pandas as pd

In [9]:
data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", None, "Eva", "Frank", "Grace", "Henry", None, "Jack"],
    "Department": ["HR", "IT", None, "Finance", "IT", "HR", "Marketing", None, "Finance", "IT"],
    "Age": [25, 30, np.nan, 28, 35, None, 29, 31, 27, np.nan],
    "Salary": [50000, 60000, 55000, np.nan, 70000, 52000, None, 65000, 58000, 62000],
    "Experience_Years": [2, 5, 3, None, 8, 2, 4, np.nan, 3, 6],
    "City": ["Delhi", "Mumbai", "Chennai", "Bangalore", None, "Delhi", "Hyderabad", "Pune", "Mumbai", None]
}

df = pd.DataFrame(data)
df

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie        NaN   NaN  55000.0               3.0    Chennai
3          104      NaN    Finance  28.0      NaN               NaN  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0        NaN
5          106    Frank         HR   NaN  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      NaN               4.0  Hyderabad
7          108    Henry        NaN  31.0  65000.0               NaN       Pune
8          109      NaN    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT   NaN  62000.0               6.0        NaN

In [ ]:
df.isna() #checking for missing values using isna() method

   Employee_ID   Name  Department    Age  Salary  Experience_Years   City
0        False  False       False  False   False             False  False
1        False  False       False  False   False             False  False
2        False  False        True   True   False             False  False
3        False   True       False  False    True              True  False
4        False  False       False  False   False             False   True
5        False  False       False   True   False             False  False
6        False  False       False  False    True             False  False
7        False  False        True  False   False              True  False
8        False   True       False  False   False             False  False
9        False  False       False   True   False             False   True

In [ ]:
df.isnull().sum() #counting the number of missing values in each column using isnull() method and sum() function

Employee_ID         0
Name                2
Department          2
Age                 3
Salary              2
Experience_Years    2
City                2
dtype: int64

In [13]:
df.fillna(0) #filling missing values with 0 using fillna() method

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie          0   0.0  55000.0               3.0    Chennai
3          104        0    Finance  28.0      0.0               0.0  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0          0
5          106    Frank         HR   0.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      0.0               4.0  Hyderabad
7          108    Henry          0  31.0  65000.0               0.0       Pune
8          109        0    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT   0.0  62000.0               6.0          0

In [15]:
df["Age"] = df["Age"].fillna(30) #filling specific column

In [16]:
df

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie        NaN  30.0  55000.0               3.0    Chennai
3          104      NaN    Finance  28.0      NaN               NaN  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0        NaN
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      NaN               4.0  Hyderabad
7          108    Henry        NaN  31.0  65000.0               NaN       Pune
8          109      NaN    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0        NaN

In [17]:
df.fillna({
    "Name": "Unknown",
    "Age": 30,
    "Salary": 0
}) #Different Values for Different Columns

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie        NaN  30.0  55000.0               3.0    Chennai
3          104  Unknown    Finance  28.0      0.0               NaN  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0        NaN
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      0.0               4.0  Hyderabad
7          108    Henry        NaN  31.0  65000.0               NaN       Pune
8          109  Unknown    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0        NaN

In [18]:
df["Age"] = df["Age"].fillna(df["Age"].mean()) #filling missing values with mean of the column

In [19]:
df["Age"] = df["Age"].fillna(df["Age"].median()) #filling missing values with median of the column

In [20]:
df["Name"] = df["Name"].fillna(df["Name"].mode()[0]) #filling missing values with mode of the column

In [21]:
df

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie        NaN  30.0  55000.0               3.0    Chennai
3          104    Alice    Finance  28.0      NaN               NaN  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0        NaN
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      NaN               4.0  Hyderabad
7          108    Henry        NaN  31.0  65000.0               NaN       Pune
8          109    Alice    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0        NaN

In [22]:
df.ffill() #forward fill method to fill missing values with the previous value in the column

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie         IT  30.0  55000.0               3.0    Chennai
3          104    Alice    Finance  28.0  55000.0               3.0  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0  Bangalore
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0  52000.0               4.0  Hyderabad
7          108    Henry  Marketing  31.0  65000.0               4.0       Pune
8          109    Alice    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0     Mumbai

In [23]:
df.bfill() #backward fill method to fill missing values with the next value in the column

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie    Finance  30.0  55000.0               3.0    Chennai
3          104    Alice    Finance  28.0  70000.0               8.0  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0      Delhi
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0  65000.0               4.0  Hyderabad
7          108    Henry    Finance  31.0  65000.0               3.0       Pune
8          109    Alice    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0        NaN

In [28]:
df.isnull().sum()

Employee_ID         0
Name                0
Department          2
Age                 0
Salary              2
Experience_Years    2
City                2
dtype: int64

In [30]:
df

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie        NaN  30.0  55000.0               3.0    Chennai
3          104    Alice    Finance  28.0      NaN               NaN  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0        NaN
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      NaN               4.0  Hyderabad
7          108    Henry        NaN  31.0  65000.0               NaN       Pune
8          109    Alice    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0        NaN

In [31]:
df['Department'] = df['Department'].fillna(df['Department'].mode()[0]) #filling missing values in Department column with mode

In [32]:
df

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0               2.0      Delhi
1          102      Bob         IT  30.0  60000.0               5.0     Mumbai
2          103  Charlie         IT  30.0  55000.0               3.0    Chennai
3          104    Alice    Finance  28.0      NaN               NaN  Bangalore
4          105      Eva         IT  35.0  70000.0               8.0        NaN
5          106    Frank         HR  30.0  52000.0               2.0      Delhi
6          107    Grace  Marketing  29.0      NaN               4.0  Hyderabad
7          108    Henry         IT  31.0  65000.0               NaN       Pune
8          109    Alice    Finance  27.0  58000.0               3.0     Mumbai
9          110     Jack         IT  30.0  62000.0               6.0        NaN

In [33]:
df.isnull().sum()

Employee_ID         0
Name                0
Department          0
Age                 0
Salary              2
Experience_Years    2
City                2
dtype: int64

In [34]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean()) #filling missing values in Salary column with mean

In [35]:
df['Experience_Years'] = df['Experience_Years'].fillna(df['Experience_Years'].mean()) #filling missing values in Experience_Years column with mean

In [39]:
df["City"] = df["City"].fillna(df["City"].mode()[0]) #filling missing values in City column with mode

In [44]:
df=df.drop("city", axis=1) #dropping the City column using drop() method

In [45]:
df

   Employee_ID     Name Department   Age   Salary  Experience_Years       City
0          101    Alice         HR  25.0  50000.0             2.000      Delhi
1          102      Bob         IT  30.0  60000.0             5.000     Mumbai
2          103  Charlie         IT  30.0  55000.0             3.000    Chennai
3          104    Alice    Finance  28.0  59000.0             4.125  Bangalore
4          105      Eva         IT  35.0  70000.0             8.000      Delhi
5          106    Frank         HR  30.0  52000.0             2.000      Delhi
6          107    Grace  Marketing  29.0  59000.0             4.000  Hyderabad
7          108    Henry         IT  31.0  65000.0             4.125       Pune
8          109    Alice    Finance  27.0  58000.0             3.000     Mumbai
9          110     Jack         IT  30.0  62000.0             6.000      Delhi

In [46]:
df.isna().sum()

Employee_ID         0
Name                0
Department          0
Age                 0
Salary              0
Experience_Years    0
City                0
dtype: int64