In [1]:
import pandas as pd

df = pd.read_csv("ipl_data.csv")

In [2]:
df.head(2)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen,NaN
1,2,2008,Chandigarh,2008-04-19,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,normal,0,Chennai Super Kings,33,0,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",MR Benson,SL Shastri,NaN

In [3]:
df.shape

(577, 18)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               577 non-null    int64
 1   season           577 non-null    int64
 2   city             570 non-null    str
 3   date             577 non-null    str
 4   team1            577 non-null    str
 5   team2            577 non-null    str
 6   toss_winner      577 non-null    str
 7   toss_decision    577 non-null    str
 8   result           577 non-null    str
 9   dl_applied       577 non-null    int64
 10  winner           574 non-null    str
 11  win_by_runs      577 non-null    int64
 12  win_by_wickets   577 non-null    int64
 13  player_of_match  574 non-null    str
 14  venue            577 non-null    str
 15  umpire1          577 non-null    str
 16  umpire2          577 non-null    str
 17  umpire3          0 non-null      float64
dtypes: float64(1), int64(5), str(12)
memory usage: 81.3 KB

In [5]:
df.describe()

,id,season,dl_applied,win_by_runs,win_by_wickets,umpire3
count,577.000000,577.000000,577.000000,577.000000,577.000000,0.0
mean,289.000000,2012.029463,0.025997,13.715771,3.363951,NaN
std,166.709828,2.486247,0.159263,23.619282,3.416049,NaN
min,1.000000,2008.000000,0.000000,0.000000,0.000000,NaN
25%,145.000000,2010.000000,0.000000,0.000000,0.000000,NaN
50%,289.000000,2012.000000,0.000000,0.000000,3.000000,NaN
75%,433.000000,2014.000000,0.000000,20.000000,6.000000,NaN
max,577.000000,2016.000000,1.000000,144.000000,10.000000,NaN

In [6]:
df.isnull().sum()

id                   0
season               0
city                 7
date                 0
team1                0
team2                0
toss_winner          0
toss_decision        0
result               0
dl_applied           0
winner               3
win_by_runs          0
win_by_wickets       0
player_of_match      3
venue                0
umpire1              0
umpire2              0
umpire3            577
dtype: int64

In [7]:
df['umpire3'].isnull().sum() # umpire3 has all missing values ; so no need of that column

np.int64(577)

In [8]:
df.drop(columns='umpire3', inplace=True)

In [9]:
df.head(1)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
0,1,2008,Bangalore,2008-04-18,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,140,0,BB McCullum,M Chinnaswamy Stadium,Asad Rauf,RE Koertzen

In [10]:
df[df['city'].isnull()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
402,403,2014,NaN,2014-04-19,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,7,PA Patel,Dubai International Cricket Stadium,Aleem Dar,AK Chaudhary
403,404,2014,NaN,2014-04-19,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,normal,0,Delhi Daredevils,0,4,JP Duminy,Dubai International Cricket Stadium,Aleem Dar,VA Kulkarni
407,408,2014,NaN,2014-04-23,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,normal,0,Chennai Super Kings,7,0,RA Jadeja,Dubai International Cricket Stadium,HDPK Dharmasena,RK Illingworth
409,410,2014,NaN,2014-04-25,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,4,0,AJ Finch,Dubai International Cricket Stadium,M Erasmus,S Ravi
410,411,2014,NaN,2014-04-25,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Chennai Super Kings,0,7,MM Sharma,Dubai International Cricket Stadium,BF Bowden,M Erasmus
415,416,2014,NaN,2014-04-28,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,5,Sandeep Sharma,Dubai International Cricket Stadium,BF Bowden,S Ravi
417,418,2014,NaN,2014-04-30,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Sunrisers Hyderabad,15,0,B Kumar,Dubai International Cricket Stadium,HDPK Dharmasena,M Erasmus

In [11]:
df[df['winner'].isnull()]

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2
241,242,2011,Delhi,2011-05-21,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,no result,0,NaN,0,0,NaN,Feroz Shah Kotla,SS Hazare,RJ Tucker
486,487,2015,Bangalore,2015-04-29,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,JD Cloete,PG Pathak
511,512,2015,Bangalore,2015-05-17,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,no result,0,NaN,0,0,NaN,M Chinnaswamy Stadium,HDPK Dharmasena,K Srinivasan

In [12]:
df.dtypes

id                 int64
season             int64
city                 str
date                 str
team1                str
team2                str
toss_winner          str
toss_decision        str
result               str
dl_applied         int64
winner               str
win_by_runs        int64
win_by_wickets     int64
player_of_match      str
venue                str
umpire1              str
umpire2              str
dtype: object

In [13]:
df['date'] = pd.to_datetime(df['date'])

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 577 entries, 0 to 576
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               577 non-null    int64
 1   season           577 non-null    int64
 2   city             570 non-null    str
 3   date             577 non-null    datetime64[us]
 4   team1            577 non-null    str
 5   team2            577 non-null    str
 6   toss_winner      577 non-null    str
 7   toss_decision    577 non-null    str
 8   result           577 non-null    str
 9   dl_applied       577 non-null    int64
 10  winner           574 non-null    str
 11  win_by_runs      577 non-null    int64
 12  win_by_wickets   577 non-null    int64
 13  player_of_match  574 non-null    str
 14  venue            577 non-null    str
 15  umpire1          577 non-null    str
 16  umpire2          577 non-null    str
dtypes: datetime64[us](1), int64(5), str(11)
memory usage: 76.8 KB

In [15]:
df['season'].nunique() # Find the total number of IPL seasons in the dataset

9

In [16]:
sorted(df['season'].unique()) # Display all unique IPL seasons

[np.int64(2008),
 np.int64(2009),
 np.int64(2010),
 np.int64(2011),
 np.int64(2012),
 np.int64(2013),
 np.int64(2014),
 np.int64(2015),
 np.int64(2016)]

In [17]:
teams = pd.concat([df['team1'], df['team2']]).unique()

len(teams)

13

In [18]:
sorted(teams)

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Mumbai Indians',
 'Pune Warriors',
 'Rajasthan Royals',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Sunrisers Hyderabad']

In [19]:
matches_per_season = df['season'].value_counts().sort_index()

matches_per_season

season
2008    58
2009    57
2010    60
2011    73
2012    74
2013    76
2014    60
2015    59
2016    60
Name: count, dtype: int64

In [20]:
for season in sorted(df['season'].unique()):
    teams = pd.concat([
        df[df['season'] == season]['team1'],
        df[df['season'] == season]['team2']
    ]).unique()

    print(season, len(teams))

2008 8
2009 8
2010 8
2011 10
2012 9
2013 9
2014 8
2015 8
2016 8

In [21]:
for season in sorted(df['season'].unique()):
    teams = sorted(pd.concat([
        df[df['season'] == season]['team1'],
        df[df['season'] == season]['team2']
    ]).unique())

    print(f"\n{season}")
    print(teams)

2008
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals', 'Royal Challengers Bangalore']

2009
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals', 'Royal Challengers Bangalore']

2010
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals', 'Royal Challengers Bangalore']

2011
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Daredevils', 'Kings XI Punjab', 'Kochi Tuskers Kerala', 'Kolkata Knight Riders', 'Mumbai Indians', 'Pune Warriors', 'Rajasthan Royals', 'Royal Challengers Bangalore']

2012
['Chennai Super Kings', 'Deccan Chargers', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Pune Warriors', 'Rajasthan Royals', 'Royal Challengers Bangalore']

2013
['Chennai Super Kings', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Pune Warriors', 'Rajasthan Royals', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']

2014
['Chennai Super Kings', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']

2015
['Chennai Super Kings', 'Delhi Daredevils', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Rajasthan Royals', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']

2016
['Delhi Daredevils', 'Gujarat Lions', 'Kings XI Punjab', 'Kolkata Knight Riders', 'Mumbai Indians', 'Rising Pune Supergiants', 'Royal Challengers Bangalore', 'Sunrisers Hyderabad']

In [22]:
df['winner'].value_counts()

winner
Mumbai Indians                 80
Chennai Super Kings            79
Royal Challengers Bangalore    70
Kolkata Knight Riders          68
Rajasthan Royals               63
Kings XI Punjab                63
Delhi Daredevils               56
Sunrisers Hyderabad            34
Deccan Chargers                29
Pune Warriors                  12
Gujarat Lions                   9
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: count, dtype: int64

In [23]:
matches_played = pd.concat([
    df['team1'],
    df['team2']
]).value_counts()

matches_played

Mumbai Indians                 140
Royal Challengers Bangalore    139
Kings XI Punjab                134
Delhi Daredevils               133
Kolkata Knight Riders          132
Chennai Super Kings            131
Rajasthan Royals               118
Deccan Chargers                 75
Sunrisers Hyderabad             62
Pune Warriors                   46
Gujarat Lions                   16
Kochi Tuskers Kerala            14
Rising Pune Supergiants         14
Name: count, dtype: int64

In [24]:
wins = df['winner'].value_counts()

matches = pd.concat([
    df['team1'],
    df['team2']
]).value_counts()

team_stats = pd.DataFrame({
    'Matches_Played': matches,
    'Matches_Won': wins
})

team_stats = team_stats.fillna(0)

team_stats['Win_Percentage'] = (
    team_stats['Matches_Won'] /
    team_stats['Matches_Played'] * 100
).round(2)

team_stats.sort_values(
    'Win_Percentage',
    ascending=False
)

                             Matches_Played  Matches_Won  Win_Percentage
Chennai Super Kings                     131           79           60.31
Mumbai Indians                          140           80           57.14
Gujarat Lions                            16            9           56.25
Sunrisers Hyderabad                      62           34           54.84
Rajasthan Royals                        118           63           53.39
Kolkata Knight Riders                   132           68           51.52
Royal Challengers Bangalore             139           70           50.36
Kings XI Punjab                         134           63           47.01
Kochi Tuskers Kerala                     14            6           42.86
Delhi Daredevils                        133           56           42.11
Deccan Chargers                          75           29           38.67
Rising Pune Supergiants                  14            5           35.71
Pune Warriors                            46           12           26.09

In [25]:
team_stats['Matches_Lost'] = (
    team_stats['Matches_Played']
    - team_stats['Matches_Won']
)

team_stats.sort_values(
    'Matches_Lost',
    ascending=False
)

,Matches_Played,Matches_Won,Win_Percentage,Matches_Lost
Delhi Daredevils,133,56,42.11,77
Kings XI Punjab,134,63,47.01,71
Royal Challengers Bangalore,139,70,50.36,69
Kolkata Knight Riders,132,68,51.52,64
Mumbai Indians,140,80,57.14,60
Rajasthan Royals,118,63,53.39,55
Chennai Super Kings,131,79,60.31,52
Deccan Chargers,75,29,38.67,46
Pune Warriors,46,12,26.09,34
Sunrisers Hyderabad,62,34,54.84,28
Rising Pune Supergiants,14,5,35.71,9
Kochi Tuskers Kerala,14,6,42.86,8
Gujarat Lions,16,9,56.25,7

In [26]:
df['toss_decision'].value_counts()

toss_decision
field    315
bat      262
Name: count, dtype: int64

In [27]:
df['toss_winner'].value_counts()

toss_winner
Mumbai Indians                 74
Kolkata Knight Riders          69
Chennai Super Kings            66
Kings XI Punjab                64
Delhi Daredevils               64
Rajasthan Royals               63
Royal Challengers Bangalore    61
Deccan Chargers                43
Sunrisers Hyderabad            30
Pune Warriors                  20
Kochi Tuskers Kerala            8
Gujarat Lions                   8
Rising Pune Supergiants         7
Name: count, dtype: int64

In [28]:
(df['toss_winner'] == df['winner']).sum()

np.int64(291)

In [29]:
round(
    (df['toss_winner'] == df['winner']).mean() * 100,
    2
)

np.float64(50.43)

In [30]:
pd.crosstab(
    df['toss_decision'],
    df['winner'] == df['toss_winner']
)

col_0          False  True
toss_decision
bat              144    118
field            142    173

In [31]:
ct = pd.crosstab(
    df['toss_decision'],
    df['winner'] == df['toss_winner']
)

(ct.div(ct.sum(axis=1), axis=0) * 100).round(2)

col_0          False  True
toss_decision
bat            54.96  45.04
field          45.08  54.92

In [32]:
df['player_of_match'].value_counts().head(15)

player_of_match
CH Gayle          17
YK Pathan         16
AB de Villiers    15
DA Warner         14
SK Raina          13
RG Sharma         13
MEK Hussey        12
MS Dhoni          12
G Gambhir         12
AM Rahane         12
V Sehwag          11
V Kohli           11
SR Watson         10
JH Kallis         10
DR Smith          10
Name: count, dtype: int64

In [33]:
df.groupby('winner')['player_of_match'].count().sort_values(ascending=False)

winner
Mumbai Indians                 80
Chennai Super Kings            79
Royal Challengers Bangalore    70
Kolkata Knight Riders          68
Kings XI Punjab                63
Rajasthan Royals               63
Delhi Daredevils               56
Sunrisers Hyderabad            34
Deccan Chargers                29
Pune Warriors                  12
Gujarat Lions                   9
Kochi Tuskers Kerala            6
Rising Pune Supergiants         5
Name: player_of_match, dtype: int64

In [34]:
df['venue'].value_counts().head(15)

venue
M Chinnaswamy Stadium                                  58
Eden Gardens                                           54
Feroz Shah Kotla                                       53
Wankhede Stadium                                       49
MA Chidambaram Stadium, Chepauk                        48
Rajiv Gandhi International Stadium, Uppal              41
Punjab Cricket Association Stadium, Mohali             35
Sawai Mansingh Stadium                                 33
Dr DY Patil Sports Academy                             17
Subrata Roy Sahara Stadium                             17
Kingsmead                                              15
SuperSport Park                                        12
Sardar Patel Stadium, Motera                           12
Brabourne Stadium                                      11
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium    11
Name: count, dtype: int64

In [35]:
for venue in df['venue'].value_counts().head(5).index:
    print("\n", venue)
    print(df[df['venue'] == venue]['winner'].value_counts().head())

 M Chinnaswamy Stadium
winner
Royal Challengers Bangalore    29
Mumbai Indians                  6
Kolkata Knight Riders           4
Chennai Super Kings             4
Kings XI Punjab                 4
Name: count, dtype: int64

 Eden Gardens
winner
Kolkata Knight Riders          33
Mumbai Indians                  8
Chennai Super Kings             4
Royal Challengers Bangalore     3
Kings XI Punjab                 2
Name: count, dtype: int64

 Feroz Shah Kotla
winner
Delhi Daredevils               19
Chennai Super Kings             5
Kings XI Punjab                 4
Royal Challengers Bangalore     4
Kolkata Knight Riders           4
Name: count, dtype: int64

 Wankhede Stadium
winner
Mumbai Indians                 29
Kings XI Punjab                 4
Chennai Super Kings             4
Royal Challengers Bangalore     3
Rajasthan Royals                2
Name: count, dtype: int64

 MA Chidambaram Stadium, Chepauk
winner
Chennai Super Kings            33
Mumbai Indians                  3
Delhi Daredevils                2
Deccan Chargers                 2
Royal Challengers Bangalore     2
Name: count, dtype: int64

In [36]:
(df['win_by_runs'] > 0).sum()

np.int64(261)

In [37]:
(df['win_by_wickets'] > 0).sum()

np.int64(307)